export const ALL_PERMISSIONS: Record<string, string[]> = {
  inventory:    ['view', 'adjust', 'move_location', 'recode', 'qa_update', 'update_ncc', 'update_prod_date', 'export'],
  inbound:      ['view', 'create', 'edit', 'scan', 'edit_pallet', 'force_edit_pallet', 'delete_pallet', 'force_delete_pallet', 'cancel', 'complete', 'uncomplete'],
  outbound:     ['view', 'prepare', 'create', 'import', 'edit', 'assign', 'unassign', 'start', 'unstart', 'scan', 'complete', 'uncomplete', 'cancel'],
  scanlog:      ['view'],
  loosepicking: ['view', 'scan', 'complete'],
  stocktake:    ['view', 'scan', 'complete'],
  locations:    ['view', 'create', 'edit', 'delete'],
  employees:    ['view'],
  user_admin:   ['view', 'create', 'edit', 'set_password', 'delete', 'manage_roles'],
  wms_settings: ['view', 'manage_warehouse', 'manage_type', 'manage_zone', 'manage_shift', 'manage_qa'],
  tms_plan:          ['view', 'create', 'edit', 'delete', 'add_vehicle', 'release', 'change_date', 'book', 'revoke', 'upload_outbound', 'upload_inbound', 'confirm_receipt'],
  tms_vehicle_types: ['view', 'create', 'edit', 'delete'],
  tms_slots:         ['view', 'create', 'edit', 'delete'],
  tms_companies:     ['view', 'create', 'edit', 'delete'],
  tms_vehicles:      ['view', 'create', 'edit', 'delete'],
  gate_registration: ['view', 'create', 'edit', 'delete', 'call', 'entry', 'exit'],
  inbound_plan:      ['view', 'create', 'edit', 'delete', 'cancel'],
  materials:         ['view', 'create', 'edit', 'delete'],
  pallet_print:      ['view', 'generate', 'reprint'],
  pallet_ops:        ['view', 'merge', 'ungroup', 'split'],
  work_skill:        ['view', 'create', 'edit', 'delete', 'assign'],
  leave:             ['view', 'request', 'approve', 'delete'],
  work_assignment:   ['view', 'create', 'edit', 'publish', 'delete', 'manage_layout', 'manage_shift_rules'],
  attendance:        ['view', 'self_log', 'edit', 'report'],
}
