export const ALL_PERMISSIONS: Record<string, string[]> = {
  inventory:    ['view', 'adjust', 'move_location', 'recode', 'qa_update', 'update_prod_date', 'export'],
  inbound:      ['view', 'create', 'scan', 'edit_pallet', 'force_edit_pallet', 'delete_pallet', 'force_delete_pallet', 'cancel'],
  outbound:     ['view', 'create', 'edit', 'assign', 'unassign', 'start', 'unstart', 'scan', 'complete', 'uncomplete', 'cancel'],
  scanlog:      ['view'],
  loosepicking: ['view', 'create', 'start', 'scan', 'complete', 'cancel'],
  stocktake:    ['view', 'create', 'scan', 'complete'],
  locations:    ['view', 'create', 'edit', 'delete'],
  employees:    ['view', 'create', 'edit', 'set_password', 'delete'],
  vehicles:     ['view', 'create', 'edit'],
  deliveries:   ['view', 'create', 'edit'],
  schedule:     ['view', 'create', 'approve'],
  wms_settings: ['view', 'manage'],
  tms:          ['view', 'book', 'manage_booking', 'upload_outbound', 'upload_inbound', 'gate_log', 'manage_slots', 'manage_companies'],
}
